#!/usr/bin/env bash
set -euo pipefail

# ================================================================
#  ADVANCIA PAYLEDGER — VPS DEPLOY (Ubuntu 22.04)
#  Run as: ssh root@76.13.77.8  (then paste this whole file)
#
#  What it does:
#  - Installs Node 20, PM2, Nginx, UFW
#  - Clones/updates the repo into /var/www/advancia
#  - Builds + starts the API via PM2 (app: advancia-api)
#  - Installs an HTTP Nginx reverse proxy for api.advanciapayledger.com
#
#  After this script:
#  - Upload env: scp 1-PAYLEDGER-BACKEND.env root@76.13.77.8:/var/www/advancia/.env
#  - Reload: pm2 reload ecosystem.config.cjs --env production
#  - Then: certbot --nginx -d api.advanciapayledger.com
# ================================================================

REPO_URL="${REPO_URL:-https://github.com/pdtribe181-prog/modullar-advancia.git}"
BRANCH="${BRANCH:-main}"
APP_DIR="${APP_DIR:-/var/www/advancia}"
DOMAIN="${DOMAIN:-api.advanciapayledger.com}"

export DEBIAN_FRONTEND=noninteractive

echo "[1/9] System packages"
apt-get update -y
apt-get install -y curl git nginx ufw build-essential ca-certificates

echo "[2/9] Node.js 22 + PM2"
if ! command -v node >/dev/null 2>&1 || [[ "$(node -v | sed 's/v//' | cut -d. -f1)" -lt 22 ]]; then
  curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
  apt-get install -y nodejs
fi
npm install -g pm2

echo "[3/9] Firewall (UFW)"
ufw allow OpenSSH >/dev/null || true
ufw allow 'Nginx Full' >/dev/null || true
ufw --force enable >/dev/null || true

echo "[4/9] App directory"
mkdir -p "$APP_DIR"

echo "[5/9] Clone or update repo"
if [[ -d "$APP_DIR/.git" ]]; then
  git -C "$APP_DIR" fetch --all --prune
  git -C "$APP_DIR" checkout "$BRANCH"
  git -C "$APP_DIR" pull --ff-only
else
  rm -rf "$APP_DIR"/*
  git clone --branch "$BRANCH" "$REPO_URL" "$APP_DIR"
fi

echo "[6/9] Install deps + build"
cd "$APP_DIR"
if [[ -f package-lock.json ]]; then
  npm ci
else
  npm install
fi
npm run build:prod

echo "[7/9] PM2 logs dir"
mkdir -p /var/log/pm2

echo "[8/9] Start (or reload) via PM2"
if pm2 describe advancia-api >/dev/null 2>&1; then
  pm2 reload ecosystem.config.cjs --env production
else
  pm2 start ecosystem.config.cjs --env production
fi
pm2 save
pm2 startup systemd -u root --hp /root >/dev/null 2>&1 || true

echo "[9/9] Nginx (HTTP reverse proxy for API)"
cat >/etc/nginx/sites-available/advancia <<NGINX
# Generated by 5-VPS-DEPLOY.sh
upstream advancia_api {
  server 127.0.0.1:3000;
  keepalive 64;
}

server {
  listen 80;
  listen [::]:80;
  server_name ${DOMAIN};

  # Allow certbot challenges if you use --webroot
  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  # Health check
  location = /health {
    proxy_pass http://advancia_api;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
  }

  # Main API
  location / {
    proxy_pass http://advancia_api;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Connection "";

    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;
  }

  # Stripe webhook: preserve raw body (disable buffering)
  location = /api/v1/stripe/webhook {
    proxy_pass http://advancia_api;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Connection "";

    proxy_buffering off;
    proxy_request_buffering off;
  }
}
NGINX

ln -sf /etc/nginx/sites-available/advancia /etc/nginx/sites-enabled/advancia
rm -f /etc/nginx/sites-enabled/default || true
nginx -t
systemctl restart nginx

echo ""
echo "✅ Deploy complete (API should be running on http://${DOMAIN})"
echo "Next:"
echo "  1) Upload env: scp 1-PAYLEDGER-BACKEND.env root@76.13.77.8:${APP_DIR}/.env"
echo "  2) Reload:     pm2 reload ecosystem.config.cjs --env production"
echo "  3) DNS A record: api -> 76.13.77.8 (Proxy OFF/grey cloud)"
echo "  4) Enable SSL:  apt-get install -y certbot python3-certbot-nginx && certbot --nginx -d ${DOMAIN}"
echo "  5) Test:       curl -s https://${DOMAIN}/health || curl -s http://${DOMAIN}/health"
